dastergon/awesome-chaos-engineering

README.md
Added Bruce and Kolton to Twitter feeds of Chaos Engineers
=> +Twitter feeds

README.md
Added Gremlin Inc's failure as a service tool
=> +Gremlin Inc

README.md
Blog of Gremlin Inc. featuring chaos engineering practices
=> + Gremlin Inc. blog

README.md
Added a lot of new links to content on failure injection and response in Culture
=> +A good bunch of talks and presentations in Culture

README.md
"Principles of Antifragile Software" is a position paper that discusses many facets of antifragility, incl. chaos engineering.
--Martin
=> adds "Principles of Antifragile Software"

README.md
added several notable folks in the chaos community
=> Twittet Chaos folks

README.md
I wrote a post a few months back talking about how our Chaos Engineering efforts have evolved over the last four years, including some stats on impact.
=> Add Failure Friday: Four Years On blog post

README.md
Added a slideshare of a presentation I gave at CF Summit Shanghai in 2015
=> Added a slideshare

README.md
Muxy is a proxy for simulating real-world distributed system failures to improve resilience in your applications.
It "mucks" with your system and application context, operating at Layers 4, 5 and 7, allowing you to simulate common failure scenarios from the perspective of an application under test; such as an API or a web application.
=> add Muxy chaos testing tool

README.md
Added Toxiproxy to the "Notable Tools" section
=> Added Toxiproxy to the "Notable Tools" section

README.md
A summary of a talk Tammy Butow did at QCon London where she talks about resilient systems, chaos engineering and high severity incident management. Links to slides are available on the linked page.
=> Add high severity incident management talk by Tammy Butow

README.md
A Chaos Engineering System for Live Analysis and Falsification of Exception-handling in the JVM
Authors: Long Zhang, Brice Morin, Philipp Haller, Benoit Baudry, Martin Monperrus
Affiliations: KTH Royal Institute of Technology, Sweden, SINTEF, Norway
=> Add a new paper about chaos engineering

README.md
for documentation see https://codecentric.github.io/chaos-monkey-spring-boot/
=> Added Chaos Monkey for Spring Boot

README.md
We've started a podcast about Chaos Engineering called Break Things On Purpose. I've added a Podcasts section and the listing for the podcast.
=> add Podcasts section and the listing for Break Things On Purpose

README.md
Included VMware Mangle, JBoss Byteman as Notable tools
=> Included VMware Mangle, JBoss Byteman as Notable tools

README.md
Adding Chaos Engineering: The Art of Breaking Things Purposefully - An article by Adrian Hornsby with the story of the GameDays, the prerequisites, the phases and the benefits of doing Chaos Engineering.
=> Add Chaos Engineering: The Art of Breaking Things Purposefully

README.md
Perses is a tool designed to give you insides to your JVM application by dynamically injecting failure/latency at the bytecode level with surgical precision.
Perses is designed with Principles of Chaos Engineering in mind.
=> Adding Perses to Notable Tools

README.md
I recently worked on a course for Linkedin Learning on Chaos Engineering and thought I would add it here.
=> Added personal course on Linkedin Learning

README.md
Hi, I've added a new book, which was released a few month ago.
=> Adding book Learning Chaos Engineering

README.md
Adding Verica chaos engineering blog
=> Adding Verica chaos engineering blog

README.md
Creating a new section focused on Chaos Gamedays
=> Creating a new section focused on Chaos Gamedays

README.md
I had the chance to see chaosmesh in action at a meetup a few days ago. I'm pretty convinced of the upcoming success of this platform.
=> Added chaosmesh.com

README.md
Added 3 links to tools I have created for AWS users
Added 1 link to a collection of chaos engineering blog posts I have created
Added 1 link to my twitter account
Thanks.
=> Adding some tools, eduction and link to twitter.

README.md
✏️ Add talks about chaos with terraform, postmortems and chaos in healthcare systems to culture section.
=> Patch to culture section

README.md
Add resources related to chaos security engineering
=> Add resources related to chaos security engineering

README.md
It was released in early April 2020. Currently reading it and very much liking it so far.
=> feat(books): Add the new O'Reilly book on CE

README.md
Hello!
I am Branko from Manning Publications. I thought this new early-access book of ours might be a good resource for the list.
Thanks for considering it!
=> Added Chaos Engineering: Crash test your applications

README.md
Adds https://github.com/github/go-fault to the tools section
=> add go-fault

README.md
CloudStrike is a security chaos engineering tool for AWS and GCP.
=> Added academic paper about CloudStrike

README.md
Signed-off-by: Bugra Derre <bugra.derre@proofdock.io>
=> Add one more tool and blog to the list of chaos engineering

README.md
This adds https://chaosengineering.news/ to the list of newsletters.
=> Add https://chaosengineering.news

README.md
Pystol is a fault injection platform allowing users to execute fault injection Actions in cloud-native environments in a controlled and prescribed way.
=> Adding Pystol

README.md
Adding one more tool to the emerging FE chaos-testing era :)
=> Add vue-chaos to list of chaos tools

README.md
Signed-off-by: Mila Wu <wuzaixuan@pingcap.com>
=> Add Chaos Mesh blog and update Chaos Mesh repo link

README.md
Add chaos studio and move existing link to Service Fabric fault injection to be an additional resource.
=> Update Azure chaos engineering entry

README.md
Add a blog about 《Chaos Engineering At Ant Group》 which practice in the field of finance
=> Add a blog about 《Chaos Engineering At Ant Group》 which practice in the field of finance
