dastergon/awesome-chaos-engineering

README.md

added Chaos Community meetup group, and www to Gremlin Inc's link.

+ Chaos meetup group. Corrected link to Gremlin

---

README.md

Pumba is a chaos testing and network emulation tool for Docker containers

add Pumba chaos testing for Docker

---

README.md

I've added Lorin Hochstein, chaos engineer @Netflix and co-author of Chaos Engineering book, to the Twitter feed section.

Add Lorin Hochstein to Twitter feeds of Chaos Engineers

---

README.md

I would like to suggest to include [PowerfulSeal](https://github.com/bloomberg/powerfulseal) in the list:
> __PowerfulSeal__ adds chaos to your Kubernetes clusters, so that you can detect problems in your systems as early as possible. It kills targeted pods and takes VMs up and down.
Full disclosure: I'm the main contributor, and I presented the tool last week at [Kubecon 2017 North America](https://events.linuxfoundation.org/events/kubecon-and-cloudnativecon-north-america/program/schedule).
Tell me what you think :-)

Suggest to include PowerfulSeal in the list

---

README.md

Pod-Reaper is a Chaos Tool for killing pods in kubernetes.  Deploying a Pod Reaper to your kubernetes namespace is a great way to validate your application and micro services can be resilient to chaos kills.  Pod Reaper is designed using environment variables that can be configured to support the chaos you require for testing (once an hour, once a minute, % of pods, etc.).  Tool was authored by Github user murasaki/BrianBerzins.

Consider adding Pod-Reaper as a Notable Tool

---

README.md

AgileAustralia is Australia's largest agile-related conference, and
is a hub for the Australian agilist community and those interested
in better ways of working.

add GameDay Agile Australia talk

---

README.md

Contains a number of useful resources for getting started with GameDay's
and chaos engineering in general.

add DiUS GameDay resources page

---

README.md

After seeing the PRs merged I double checked and apologies, it seems dropping the protocol made this a GitHub-relative link that wasn't an issue with my local machine. 
This fixes the broken URL.

fix GameDay resources link

---

README.md

[Byte-Monkey](https://github.com/mrwilson/byte-monkey) is a bytecode-level fault injection tool for the JVM. It works by instrumenting application code on the fly to deliberately introduce faults like exceptions and latency.

Add Byte-Monkey into Notable Tools

---

README.md

Otherwise a relative path to the github repo is used instead

Correct URL for ChaosCOnf

---

README.md

Add Cthulhu tool, a Chaos Engineering tool that helps to evaluate the resiliency of microservice systems. It does that by simulating various disaster scenarios against a target infrastructure in a data-driven manner. https://www.xmatters.com

Add Cthulhu tool.

---

README.md

The Maelstrom paper at OSDI'18 describes how Facebook runs a new type of DR (Disaster Recover) tests called _drain tests_ as well as the tooling and experiences that automate continuous drain tests. The same tooling is used in mitigating real datacenter-level disasters just like running a drain test.

Adding drain tests (a new type of DR tests) published at OSDI

---

README.md

Unfortunately, the paper on Lineage-driven Fault Injection (https://people.eecs.berkeley.edu/~palvaro/molly.pdf) is no longer available, it results in a resource not found.

Remove paper on lineage-driven Fault Injection 

---

README.md

Adding Link to ChaosKube, which periodically kills random pods in your Kubernetes cluster.

Adding ChaosKube

---

README.md

Adding chaos-mesh, a cloud-native Chaos Engineering platform that orchestrates chaos on Kubernetes environments.

Add chaos-mesh, a cloud-native Chaos Engineering platform

---

README.md

A couple of the links in **Education** had updated, two of them without re-directs. Thought it'd be easier to steer the traffic directly without the additional search :)

Education: update Gremlin blog links

---

README.md

Chaos Engine is an application for creating random Chaos Events in cloud applications to test resiliency. It follows the Principles of Chaos to create random faults (experiments) that could reasonably occur in a real application deployment.
Chaos Engine makes intelligent decisions in how and when to create experiments. When properly configured, experiments can be restricted to occur only during normal business hours (i.e., no pager alerts).
Chaos Engine currently supports Amazon Web Services, Pivotal Cloud Foundry, and Kubernetes. We have future plans to add support for Google Cloud Platform.

Adding Link to Chaos Engine

---

README.md

**Context**:
Adding [Kraken](https://github.com/openshift-scale/kraken) - a Chaos and resiliency testing tool for Kubernetes and OpenShift.
**Descirption**:
Kraken injects deliberate failures into Kubernetes/OpenShift clusters to check if it is resilient to failures.

Add OpenShift Kraken Chaos tool

---

README.md

Changed her last name / changed her twitter handle. Old twitter redirects: https://twitter.com/tammybutow

Fix Tammy Bryant twitter

---

README.md

Adding `Chaos Experimentation Framework, an open-source framework built on top of Envoy Proxy`

Added Chaos Experimentation Framwork

---

README.md

This PR adds a link to the HashiCorp learn tutorial that explains Chaos engineering and how a service mesh can be used to help pass experiments. The tutorial includes a free hands-on lab environment.

docs: added link to the HashiCorp chaos tutorial

---

README.md

This PR adds Chaos Frontend Toolkit to the list of tools.
Chaos Frontend Toolkit is a browser extension (Chrome, FF, Edge) that applies Chaos Engineering experiments to web apps.
The experiments cover network, timers, history, accessibility, localization, inputs, ...
(Re-opened from #114 after a failed rebase)

Add Chaos Frontend Toolkit to the list of tools
